before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo bash -c "echo 'foreign-architecture i386' > /etc/dpkg/dpkg.cfg.d/multiarch"
  - sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc 
  - sudo apt-add-repository 'deb http://repos.codelite.org/wx3.0-1/ubuntu/ precise universe'
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-mark hold oracle-java7-installer oracle-java8-installer
  - sudo apt-get update
  - sudo apt-get install --reinstall linux-libc-dev
  - sudo apt-get install -y libwxgtk3.0-dev libboost-dev cmake libc6-dev libc6-dev-i386 multiarch-support cpp g++ gcc gcc-multilib libf2c2:i386 libf2c2-dev:i386 f2c:i386 libboost-system-dev libboost-thread-dev
install: 
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DDISTRIBUTION=precise -DARCHITECTURE=amd64 ..
  - make
  - sudo make install
compiler: gcc
script: ctest -V
